docs: adr for the tech stack
fidildev/fettle-ui pull request #22
Opened 2023-07-21 04:30 UTC by tylerkron

2023-07-21 04:35 UTC, JacobBrauchler approved these changes

2023-07-22 02:26 UTC, milehiimikey requested changes

2023-07-22 02:26 UTC, milehiimikey commented on docs/adr/0003-fe-stack.md
> +We need to decide what javascript framework to use to make the first version of Fettle-UI. FIDIL is currently a small startup with limited frontend experience. For this reason, it's best to use a fra
I take it we don't want anyone who likes Vue? We think its boring and not cutting edge, so if you like it.... 🖕

2023-07-22 02:26 UTC, milehiimikey commented on docs/adr/0003-fe-stack.md
> +We will use [vue.js](https://vuejs.org/) using [Nuxt](https://nuxt.com/). We will also use [PrimeVue](https://primevue.org/) as it is a popular component library.
This doesn't tell me why its fixing the context of the problem.

2023-07-22 02:26 UTC, milehiimikey commented on docs/adr/0003-fe-stack.md
> +- [PrimeVue](https://primevue.org/)
This ADR says its tech stack, this seems like its naming 3 of the FE tools used in a much larger tech stack.

2023-07-22 02:26 UTC, milehiimikey commented on docs/adr/0003-fe-stack.md
> +There are a bajillion Component Libraries. We might choose a different one after getting experience with the chosen one in this ADR. Alternatives include:
Why didn't we choose any of these?

2023-07-22 03:34 UTC, tylerkron commented on docs/adr/0003-fe-stack.md
> +We need to decide what javascript framework to use to make the first version of Fettle-UI. FIDIL is currently a small startup with limited frontend experience. For this reason, it's best to use a fra
Good point, reworded

2023-07-22 03:36 UTC, tylerkron commented on docs/adr/0003-fe-stack.md
> +We will use [vue.js](https://vuejs.org/) using [Nuxt](https://nuxt.com/). We will also use [PrimeVue](https://primevue.org/) as it is a popular component library.
Added more context to this.

2023-07-22 03:37 UTC, tylerkron commented on docs/adr/0003-fe-stack.md
> +- [PrimeVue](https://primevue.org/)
Another good point, renaming to FE Framework

2023-07-22 03:41 UTC, tylerkron commented on docs/adr/0003-fe-stack.md
> +There are a bajillion Component Libraries. We might choose a different one after getting experience with the chosen one in this ADR. Alternatives include:
Left a comment about that.

2023-07-23 15:39 UTC, milehiimikey approved these changes

2023-07-23 18:30 UTC, merged